/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config workers/leaderboard-snapshots/wrangler.jsonc --include-runtime=false` (hash: 2a73b83e5c52ff63ff73e45c46ab7686)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/leaderboard-snapshots/index");
		durableNamespaces: "SnapshotPublisher";
	}
	interface Env {
		LEADERBOARD_SNAPSHOTS: R2Bucket;
		LEADERBOARD_DB: D1Database;
		PUBLISHER: DurableObjectNamespace<import("./workers/leaderboard-snapshots/index").SnapshotPublisher>;
	}
}
interface Env extends Cloudflare.Env {}
